using SerousEnergyLib.API.Machines;
using SerousEnergyLib.Items;
using System;
using System.Text.RegularExpressions;
using Terraria.ModLoader;
using Terraria.ModLoader.IO;

namespace SerousEnergyLib.API.Upgrades {
	/// <summary>
	/// The base type for an upgrade that can be placed in a machine
	/// </summary>
	public abstract class BaseUpgrade : ModType {
		/// <summary>
		/// The unique ID for this upgrade type
		/// </summary>
		public int Type { get; protected private set; }

		/// <summary>
		/// The translations for the display name of this upgrade.
		/// </summary>
		public ModTranslation DisplayName { get; private set; }

		/// <summary>
		/// The translations for the tooltip of this item.
		/// </summary>
		public ModTranslation Tooltip { get; private set; }

		/// <summary>
		/// How many instances of this upgrade are permitted on any machine
		/// </summary>
		public abstract int MaxUpgradesPerMachine { get; }

		/// <summary>
		/// The item ID for the <see cref="BaseUpgradeItem"/> that uses this upgrade
		/// </summary>
		public abstract int ItemType { get; }

		#pragma warning disable CS1591
		protected sealed override void Register() {
			ModTypeLookup<BaseUpgrade>.Register(this);

			DisplayName = LocalizationLoader.GetOrCreateTranslation(Mod, $"MachineUpgradeName.{Name}");
			Tooltip = LocalizationLoader.GetOrCreateTranslation(Mod, $"MachineUpgradeTooltip.{Name}", true);

			Type = UpgradeLoader.Register(this);
		}

		public sealed override void SetupContent() {
			AutoStaticDefaults();
			SetStaticDefaults();
		}

		/// <summary>
		/// Automatically sets certain static defaults. Override this if you do not want the properties to be set for you.
		/// </summary>
		public virtual void AutoStaticDefaults() {
			if (DisplayName.IsDefault())
				DisplayName.SetDefault(Regex.Replace(Name, "([A-Z])", " $1").Trim());
		}

		/// <summary>
		/// Whether this upgrade can be applied to the specified machine
		/// </summary>
		public abstract bool CanApplyTo(IMachine machine);

		/// <summary>
		/// Return a modifier for power conumption in an <see cref="IPoweredMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		public virtual StatModifier GetPowerConsumptionMultiplier(int upgradeStack) => StatModifier.Default;

		/// <summary>
		/// Return a modifier for power generation in an <see cref="IPowerGeneratorMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		public virtual StatModifier GetPowerGenerationMultiplier(int upgradeStack) => StatModifier.Default;

		/// <summary>
		/// Return a modifier for the maximum power capacity in an <see cref="IPoweredMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		public virtual StatModifier GetPowerCapacityMultiplier(int upgradeStack) => StatModifier.Default;

		/// <summary>
		/// Return a modifier for the maximum fluid storage capacity for a fluid storage in an <see cref="IFluidMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		public virtual StatModifier GetFluidCapacityMultiplier(int upgradeStack) => StatModifier.Default;

		/// <summary>
		/// Return an addition to the item stack generated by an <see cref="IItemOutputGeneratorMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		/// <param name="originalStack">The item stack before applying this upgrade</param>
		public virtual int GetItemOutputGeneratorExtraStack(int upgradeStack, int originalStack) => 0;

		/// <summary>
		/// Return a modifier for the fluid product quantity generated by an <see cref="IFluidOutputGeneratorMachine"/> here
		/// </summary>
		/// <param name="upgradeStack">How many instances of this upgrade are stored in the machine</param>
		public virtual StatModifier GetFluidOutputGeneratorProductMultiplier(int upgradeStack) => StatModifier.Default;
	}

	public abstract class BaseUpgrade<T> : BaseUpgrade where T : BaseUpgradeItem {
		public sealed override int ItemType => ModContent.ItemType<T>();
	}
}
